apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: nginx:alpine
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/484123688626/analytics-service-queue"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
