apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-publisher
  labels:
    app: order-publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-publisher
  template:
    metadata:
      labels:
        app: order-publisher
    spec:
      containers:
        - name: order-publisher
          image: 484123688626.dkr.ecr.us-east-1.amazonaws.com/order-publisher:latest
          ports:
            - containerPort: 3000
          env:
            - name: AWS_SNS_TOPIC_ARN
              value: "arn:aws:sns:us-east-1:484123688626:order-events"
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-publisher-service
spec:
  selector:
    app: order-publisher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
